# .github/workflows/build-and-upload.yml
name: Build and Upload rofi-calc Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository (ensures we have configure.ac at root)
      - name: Checkout repository
        uses: actions/checkout@v4
        # Using v4 ensures no transitive dependency on older artifact actions 

      # 2. Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkg-config \
            rofi-dev \
            qalc
        # This matches instructions: Ubuntu: apt install rofi-dev qalc libtool plus autotools :contentReference[oaicite:8]{index=8}

      # 3. Generate autotools files (must split into separate commands)
      - name: Generate autotools files
        run: |
          mkdir -p m4
          autoreconf -i
        # Splitting commands ensures that 'autoreconf' sees configure.ac :contentReference[oaicite:9]{index=9}

      # 4. Configure in a separate build directory
      - name: Configure
        run: |
          mkdir -p build
          cd build
          ../configure
        # Creates out-of-tree build dir so Makefiles and artifacts stay isolated :contentReference[oaicite:10]{index=10}

      # 5. Compile with all available CPU cores
      - name: Build
        run: |
          cd build
          make -j$(nproc)
        # After this, 'build/rofi-calc' is the compiled plugin :contentReference[oaicite:11]{index=11}

      # 6. Upload the compiled binary as an artifact (use v4)
      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: rofi-calc-binary
          path: build/rofi-calc
        # Uploading the file allows you to download it from the run’s Artifacts tab 
