name: Build and Upload rofi-calc Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the workflow-only repo (which has no rofi-calc source)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Clone the official rofi-calc repository into 'rofi-calc-src/'
      - name: Clone rofi-calc upstream
        run: |
          git clone --depth 1 https://github.com/svenstaro/rofi-calc.git rofi-calc-src
        # --depth 1 fetches only the latest commit, speeding up the clone

      # 3. Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkg-config \
            rofi-dev \
            qalc
        # Installs autotools, rofi headers (rofi-dev), and qalc

      # 4. Generate autotools files inside the cloned source
      - name: Generate autotools files
        working-directory: rofi-calc-src
        run: |
          mkdir -p m4
          autoreconf -i
        # By specifying working-directory, we ensure configure.ac is found

      # 5. Configure & build inside 'rofi-calc-src/build'
      - name: Configure & Build
        working-directory: rofi-calc-src
        run: |
          mkdir -p build
          cd build
          ../configure
          make -j$(nproc)

      # 6. Upload the compiled rofi-calc binary
      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: rofi-calc-binary
          path: rofi-calc-src/build/rofi-calc
        # The path points to the compiled binary inside the cloned directory
