name: Build and Upload rofi-calc Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the (empty) repo
      - name: Checkout repository
        uses: actions/checkout@v4
        # Using v4 avoids any hidden dependency on deprecated artifact actions. 

      # 2. Clone the upstream rofi-calc source
      - name: Clone rofi-calc upstream
        run: |
          git clone --depth 1 https://github.com/svenstaro/rofi-calc.git rofi-calc-src
        # --depth 1 fetches only the latest commit to speed up cloning. :contentReference[oaicite:5]{index=5}

      # 3. Install build dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            pkg-config \
            rofi-dev \
            qalc
        # Matches Ubuntu instructions: apt install rofi-dev qalc libtool plus autotools. :contentReference[oaicite:6]{index=6}

      # 4. Generate autotools files in the cloned directory
      - name: Generate autotools files
        working-directory: rofi-calc-src
        run: |
          mkdir -p m4
          autoreconf -i
        # Splitting commands ensures `autoreconf` sees configure.ac in rofi-calc-src. 

      # 5. Configure & build out-of-tree
      - name: Configure & Build
        working-directory: rofi-calc-src
        run: |
          mkdir -p build
          cd build
          ../configure
          make -j$(nproc)
        # After this, the compiled plugin is at rofi-calc-src/build/.libs/calc.so. :contentReference[oaicite:8]{index=8}

      # 6. Upload the shared object (calc.so) as an artifact
      - name: Upload compiled plugin
        uses: actions/upload-artifact@v4
        with:
          name: rofi-calc-plugin
          path: rofi-calc-src/build/.libs/calc.so
        # Path must point to .libs/calc.so—the actual output of `make`. :contentReference[oaicite:9]{index=9}
